dhango-pm/project_Maneger/Project_Maneger/urls.py
from django.contrib import admin
from django.urls import path,include
import debug_toolbar.toolbar
from django.utils.translation import gettext
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.site.site_header=gettext("Projects Manegment")
admin.site.site_title=gettext("Projects Manegment")

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include("accounts.urls")),
    path("",include("project.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns+=staticfiles_urlpatterns()

dhango-pm/project_Maneger/project/urls.py
from django.urls import path,include
from . import views
urlpatterns = [
    path("Project/Project_list",views.ProjectListView.as_view(),name="Project_list"), # type: ignore
    path("Project/Create",views.ProjectCreatView.as_view(),name="Project_create"), # type: ignore
    path("Project/edit/<int:pk>",views.ProjectUpdateView.as_view(),name="Project_update"), # type: ignore
    path("Project/delete/<int:pk>", views.ProjectDeleteView.as_view(), name="Project_delete"),
    path("Task/Create",views.TaskCreateView.as_view(),name="Task_Create"), # type: ignore
    path("Task/Update/<int:pk>",views.TaskUpdateView.as_view(),name="Task_update"),
    path("Task/Delete/<int:pk>",views.TaskDeleteView.as_view(),name="Task_delete"), # type: ignore

]

dhango-pm/project_Maneger/project/models.py
from django.db import models
from django.conf.global_settings import AUTH_USER_MODEL
# Create your models here.
from django.utils.translation import gettext

    

class Category(models.Model):
    name=models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.name
    class Mete:
        verbose_name=gettext('Categorys')
        verbose_name_plural=gettext('Categorys')
    

class projectStatus(models.IntegerChoices):
    PENDING=1,gettext("pending")
    COMPLETED=2,gettext("completed")
    POSTPOEND=3,gettext("postpoend")
    CANCELED=4,gettext("canceled")



class Project(models.Model):
    title=models.CharField(null=False)
    descreption=models.TextField()
    satutes=models.IntegerField(
        choices=projectStatus.choices,
        default=projectStatus.PENDING
    )
    created_at=models.DateTimeField(auto_now_add=True)
    Updated_at=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.PROTECT)
    user=models.ForeignKey(AUTH_USER_MODEL,on_delete=models.CASCADE,null=True)
    def __str__(self) -> str:
        return self.title
    class Mete:
        verbase_name=gettext('Project')
        verbase_name_plural=gettext('Project')
    

class Task(models.Model):
    descreption=models.TextField()
    is_completed=models.BooleanField(default=False)
    project=models.ForeignKey(Project,on_delete=models.CASCADE)
    def __str__(self) -> str:
        return self.descreption
    

dhango-pm/project_Maneger/project/forms.py
from django import forms
from . import models
from django.utils.translation import gettext

attrs={
    "class":"form-control"
    }

class projectCreatForm(forms.ModelForm):
    class Meta:
        model=models.Project
        fields=["category","title","descreption"]
        labels={
            'category':gettext("category"),
            'title':gettext('title'),
            'descreption':gettext('descreption')
        }
        widgets={
            'category':forms.Select(attrs=attrs),
            'title':forms.TextInput(attrs=attrs),
            'descreption':forms.Textarea(attrs=attrs)
}

class projectUpdateForm(forms.ModelForm):
    class Meta:
        model=models.Project
        fields=["category","title","satutes"]
        widgets={
            'category':forms.Select(attrs=attrs),
            'title':forms.TextInput(attrs=attrs),
            'satutes':forms.Select(attrs=attrs)
}

dhango-pm/project_Maneger/project/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from . import models,forms
from django.views.generic import ListView,CreateView,UpdateView,DeleteView
from django.urls import reverse,reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
# Create your views here.


class ProjectListView(LoginRequiredMixin,ListView):
    model=models.Project
    template_name="project/list.html"
    paginate_by=6 #limt how card can apper
    def get_queryset(self):
        queryset= super().get_queryset()
        where={'user_id':self.request.user}
        q=self.request.GET.get("q",None)
        if q:
            where['title__icontains']=q
        return queryset.filter(**where)


class ProjectCreatView(LoginRequiredMixin,CreateView):
    model=models.Project
    form_class=forms.projectCreatForm
    template_name="project/creat.html"
    def get_success_url(self):
        return "Project_list"
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)

class ProjectUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model=models.Project
    form_class=forms.projectUpdateForm
    template_name="project/update.html"
    def test_func(self):
        return self.get_object().user_id==self.request.user.id



    def get_success_url(self):
        return reverse("Project_update", args=[self.object.id]) # type: ignore

from django.urls import reverse_lazy

class ProjectDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = models.Project
    template_name = "project/delete.html"
    success_url = reverse_lazy('Project_list')
    def test_func(self):
        return self.get_object().user_id==self.request.user.id

    
class TaskCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = models.Task
    fields = ["project", "descreption"]
    template_name = 'project/update.html'
    http_method_names = ['post']

    def test_func(self):
        project_id = self.request.POST.get('project', '')
        return models.Project.objects.get(pk=project_id).user_id == self.request.user.id

    def get_success_url(self):
        return reverse("Project_update", args=[self.object.project.id])
    
class TaskUpdateView(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
    model=models.Task
    fields=["is_completed"]
    http_method_name=["post"]#to make the path to just create

    def test_func(self):
        return self.get_object().project.user_id==self.request.user.id

    def get_success_url(self):
        return reverse("Project_update", args=[self.object.project.id])    
    
class TaskDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model=models.Task

    def test_func(self):
        return self.get_object().project.user_id==self.request.user.id

    def get_success_url(self):
        return reverse("Project_update", args=[self.object.project.id])   

dhango-pm/project_Maneger/project/templates/Project/Task.html
{% load i18n %}

<ul class="list-group">
    {% for task in object.task_set.all %}
    <li class="list-group-item d-flex">
        <form method="post" action="{% url 'Task_update' task.id %}" class="my-auto me-2">
            {% csrf_token %}
            <input
            class="form-check-input"
             type="checkbox" 
            name="is_completed" 
            {% if task.is_completed %} checked {% endif %}
            onchange="this.form.submit()"
            />
        </form>
        <p class="my-auto me-auto">
            {{ task.descreption }}
        </p>
        
        <form method="post" action="{% url 'Task_delete' task.id %}">
            {% csrf_token %}
            <button type="submit" class="btn"> <i class="bi bi-trash text-danger"></i>{% trans 'Delete' %}</button>
        </form>
    </li>
    {% endfor %}
</ul>

<div class="card">
    <form method="post" action="{% url 'Task_Create'  %}" class="d-flex">
        {% csrf_token %}
        <div class="input-group">
            <input type="hidden" value="{{project.id}}" name="project">
            <input type="text" name="description" class="form-control" placeholder="{% trans 'New task' %}">
            <input type="submit" class="btn btn-outline-dark" value="{% trans 'Add' %}">
        </div>
    </form>
</div>

dhango-pm/project_Maneger/project/templates/Project/creat.html
{% extends "base.html" %}
{%load i18n%}


{%block content%}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="card col-md-6 px-0">
            <div class="card-header">
                <h3 class="mb-0 py-2">{% trans "New Project" %}</h3>
            </div>
            <div class="card-body">
                {% if error_message %}
                <div class="alert alert-danger">{{ error_message }}</div>
                {% endif %}
                <form method="post">
                    {%csrf_token%}
                    {% include "common/form.html" with form=form %}
                    <button class="btn btn-success"> {% translate 'create' %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock content%}

dhango-pm/project_Maneger/project/templates/Project/delete.html
{% extends "base.html" %}

{%load i18n%}
{%block content%}
<h2>{% trans 'Alert' %}</h2>
<form method="post">
    {%csrf_token%}
    <p class="text-muted my-4">
    {% trans 'Are you sure to delete' %} {{project.title}} ? 
</p>
</form>
    <form method="POST">
        {%csrf_token%}
        <input type="submit" class="btn btn-danger" value="Delete.">

    </form>


{%endblock content%}

dhango-pm/project_Maneger/project/templates/Project/list.html
{% extends "base.html" %}
{% load i18n %}
{% load humanize %}
{% block content %}
    <div class="d-flex">
        <h3 class="me-auto">{% trans 'My Project' %}</h3>
        <div>
            <a href="{% url 'Project_create' %}" class="btn btn-outline-success">
                <i class="bi bi-plus-lg"></i> {% trans 'New Project' %}
            </a>
        </div>
    </div>
    <div class="row my-5">
        {% for project in object_list %}
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-body">
                    <p>
                        <span class="badge rounded-pill bg-dark">
                            {{ project.get_satutes_display }}
                        </span>
                    </p>
                    <h3 class="card-title fs-6">{{ project.title }}</h3>
                    <p class="card-text text-muted small">{{ project.description }}</p>
                    <div class="d-flex">
                        <span class="me-auto text-muted small">
                            <i class="bi bi-clock"></i>
                            <time datetime="{{ project.created_at|date:'c' }}">
                                {{ project.created_at|naturaltime }}
                            </time>
                        </span>
                        <a href="{% url 'Project_update' project.id %}" class="btn btn-sm btn-outline-dark mx-1">
                            {% trans "Edit" %}
                        </a>
                        <a href="{% url 'Project_delete' project.id %}" class="btn btn-sm btn-outline-danger">
                            <i class="bi bi-trash"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-md-12">
            <div class="h-100 p-5 bg-white border rounded-3 text-center">
                <p>{% trans 'There are no projects' %}</p>
                <p><i class="bi bi-emoji-frown fs-1"></i></p>
                <p>
                    <a href="{% url 'Project_create' %}" class="btn btn-outline-success">
                        <i class="bi bi-plus-lg"></i> {% trans 'New Project' %}
                    </a>
                </p>
            </div>
        </div>
        {% endfor %}
        {% if page_obj.paginator.count > 0 %}
    <div class="d-flex justify-content-center bd-highlight mb-3">
        <nav>
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                            {% trans 'Previous' %}
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            {% trans "Previous" %}
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{page_obj.next_page_number}}">
                            {% trans 'Next' %}
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">
                            {% trans "Next" %}
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endif %}
{% endblock %}

dhango-pm/project_Maneger/project/templates/Project/update.html
{% extends "base.html" %}
{% load humanize %}
{%load i18n%}


{%block content%}
<nav aria-label="breadcrump">
    <ol class="breadcrump">
        <li class="breadcrump-item active " aria-current="page">
            <h5>
                {{object.title}}
            </h5>
        </li>
    </ol>
</nav>

<div class="row">
    <div class="col-md-3">
        <form method="post">
            <div class="card">
                <div class="card-body">
                    {%csrf_token%}
                    {% for field in form %}
                    <div class="mb-3">
                        {{field}}
                    </div>
                    {% endfor %}
                    <div class="d-flex mt-2">
                        <span class="me-auto text-muted small">
                            <i class="bi bi-clock"></i>
                            <time datetime="{{ object.created_at|date:'c' }}">
                                {{ project.created_at|naturaltime }}
                            </time>
                        </span>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="d-grid gap-2">
                        <button class="btn btn-success">
                            <i class="bi bi-save"></i>
                            {% trans "save" %}
                        </button>
                    </div>
                    <div class="card-footer">
                    <div class="d-grid gap-2">
                        <button class="btn btn-danger">
                            <i class="bi bi-trash"></i>
                            {% trans "delete" %}
                        </button>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
    <div class="col-md-9">
        {%include "project/Task.html" with project=object %}
    </div>
</div>
{%endblock content%}